version: '3.3'

services:

  checkinout-db:
    image: mysql:latest
    networks:
      - checknet
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Europe/Brussels
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+01:00'
      ]

  checkinout-app:
    image: yilmazchef/checkinout:latest
    restart: on-failure
    environment:
      WAIT_HOSTS: db:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://checkinout-db:3306/checkinoutdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - checknet
    ports:
      - "443:8443"
