version: "3.9"

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'checkinoutdb'
      MYSQL_ROOT_PASSWORD: 'pass'
      TZ: Europe/Brussels
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+01:00'
      ]
    volumes:
      - db-data:/var/lib/mysqlql/data
    networks:
      - spring-mysql
    ports:
      - "3443:3306"

  app:
    build: .
    restart: on-failure
    environment:
      WAIT_HOSTS: db:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/checkinoutdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - spring-mysql
    ports:
      - "443:8443"
volumes:
  db-data: null
networks:
  spring-mysql: null
