version: '3.3'

services:

  checkinout-db:
    image: mysql:latest
    restart: unless-stopped
    networks:
      - checknet
    ports:
      - "3443:3306"
    environment:
      - MYSQL_DATABASE=checkinout_prod
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - TZ=Europe/Brussels

  checkinout-app:
    image: yilmazchef/checkinout:latest
    restart: on-failure
    depends_on:
      - checkinout-db
    networks:
      - checknet
    links:
      - checkinout-db:checkinout-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://checkinout-db:3306/checkinout_prod
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
    ports:
      - "443:8443"

networks:
  checknet:
    attachable: true
