version: "3.9"
services:

  checkinout_dev_appserver:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - checkinout_dev_database_server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://checkinout_dev_database_server:5432/checkinoutdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - checkinout_development_network
    volumes:
      - checkinout_application_volume:/var/lib/checkinout

  checkinout_dev_database_server:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=checkinoutdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - checkinout_development_network
    volumes:
      - checkinout_database_volume:/var/lib/postgresql/data

  checkinout_dev_database_admin:
    image: adminer:latest
    restart: always
    ports:
      - "9090:8080"
    networks:
      - checkinout_development_network

networks:
  checkinout_production_network:
  checkinout_development_network:


volumes:
  checkinout_database_volume: {}
  checkinout_application_volume: {}
