version: '3.9'

services:

  checkinout-db:
    image: mysql:latest
    restart: unless-stopped
    networks:
      - checknet
    ports:
      - "3333:3306"
    environment:
      - MYSQL_DATABASE=checkinout_prod
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Europe/Brussels
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+01:00'
      ]

  checkinout-app:
    image: yilmazchef/checkinout:latest
    restart: on-failure
    depends_on:
      - checkinout-db
    networks:
      - checknet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://checkinout-db:3306/checkinout_prod
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8888:8443"

networks:
  checknet:
    attachable: true
