version: '3.3'

services:

  checkinout_db_server:
    container_name: checkinout_db_server
    image: mysql:latest
    restart: unless-stopped
    networks:
      - check_net
    ports:
      - "3999:3306"
    environment:
      - MYSQL_DATABASE=checkinout_dev
      - MYSQL_USER=checkinout
      - MYSQL_PASSWORD=checkinout
      - MYSQL_ROOT_PASSWORD=toor 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  checkinout_db_admin:
    container_name: checkinout_db_admin
    image: adminer
    restart: always
    links:
      - "checkinout_db_server:checkinout_db_server"
    depends_on:
      checkinout_db_server:
        condition: service_healthy
    networks:
      - check_net
    ports:
      - "1999:8080"

  checkinout_app:
    container_name: checkinout_app
    image: yilmazchef/checkinout:latest
    restart: always
    links:
    - "checkinout_db_server:checkinout_db_server"
    depends_on:
      checkinout_db_server:
        condition: service_healthy
    networks:
      - check_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://checkinout_db_server:3306/checkinout_dev?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    ports:
      - "9999:8080"

networks:
  check_net:
    attachable: true

