version: "3.3"

services:

  checkinout_database_server:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'checkinoutdb'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3333:3306"

  checkinout_database_admin:
    image: adminer:latest
    restart: always
    depends_on:
      - checkinout_database_server
    ports:
      - "9090:8080"

  webapp:
    image: yilmazchef/checkinout
    restart: on-failure
    depends_on:
      - checkinout_database_server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://checkinout_database_server:3306/checkinoutdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
    links:
      - checkinout_database_server
    ports:
      - "443:8443"


