server:
  port: ${PORT:8080}
  # ssl:
  #   key-store: classpath:testy.p12
  #   key-store-password: P@ssw0rd
  #   keyStoreType: PKCS12

logging.level:
  org.atmosphere: warn

spring.mustache.check-template-location: false
vaadin.whitelisted-packages: com/vaadin,org/vaadin,it/vkod
vaadin.pnpm.enable: false

spring:
  profiles:
    active: "production"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        search:
          backend:
            directory:
              type: local-heap
  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      roles: ${SPRING_SECURITY_ROLES}
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_PASSWORD:chefsandbox@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:1q2w3e4rP@ssw0rd}
    properties:
      mail:
        smtp.auth: true
        smtp.starttls.enable: true

  application:
    name: checkinout
  sql:
    init:
      mode: always

logging:
  level:
    org.zalando.logbook: TRACE




